service:
  name: discovery-api
  port: 80
  auth_string: ""

ingress:
  enabled: true
  scheme: ""
  subnets: ""
  security_groups: "" #Load balancer Security Group
  dnsZone: ""
  certificate_arn: ""

image:
  name: 199837183662.dkr.ecr.us-east-2.amazonaws.com/scos/discovery-api
  tag: latest

monitoring:
  targetPort: 80

resources:
  limits:
    memory: 512Mi
    cpu: 1
  requests:
    memory: 512Mi
    cpu: 100m

nodeSelector: {}

tolerations: []

affinity: {}

redis:
  host: redis.external-services

presto:
  url: "http://kdp-kubernetes-data-platform-presto.kdp:8080"
  catalog: "hive"
  schema: "default"
