service:
  name: discovery-api
  port: 80
  auth_string: ""

ingress:
  enabled: true
  scheme: ""
  subnets: ""
  security_groups: "" #Load balancer Security Group
  dns_zone: ""
  certificate_arn: ""

image:
  name: 199837183662.dkr.ecr.us-east-2.amazonaws.com/scos/discovery-api
  tag: latest

monitoring:
  targetPort: 80

kyloCreds:
  user: ""
  password: ""

resources:
  limits:
    memory: 512Mi
    cpu: 1
  requests:
    memory: 512Mi
    cpu: 100m

nodeSelector: {}

tolerations: []

affinity: {}

redis:
  host: redis.external-services

kafka:
  brokers: streaming-service-kafka-bootstrap.streaming-prime:9092
  topic: dataset-registry
  consumerGroup: discovery-dataset-consumer