apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: discovery-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: discovery-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: discovery-api
  template:
    metadata:
      labels:
        app: discovery-api
    spec:
      containers:
      - name: discovery-api
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
          - name: REDIS_HOST
            value: {{ .Values.redis.host }}
          - name: PRESTO_URL
            value: {{ .Values.presto.url }}
          - name: PRESTO_CATALOG
            value: {{ .Values.presto.catalog }}
          - name: PRESTO_SCHEMA
            value: {{ .Values.presto.schema }}
          - name: HOST
            value: data.{{ .Values.ingress.rootDnsZone }}
          - name: ALLOWED_ORIGINS
            value: {{ .Values.ingress.rootDnsZone }},{{ .Values.ingress.dnsZone }}
          - name: LDAP_HOST
            valueFrom:
              secretKeyRef:
                name: ldap
                key: host
          - name: LDAP_BASE
            valueFrom:
              secretKeyRef:
                name: ldap
                key: base_dn
          - name: LDAP_USER
            valueFrom:
              secretKeyRef:
                name: ldap
                key: user
          - name: LDAP_PASS
            valueFrom:
              secretKeyRef:
                name: ldap
                key: password
          - name: GUARDIAN_KEY
            valueFrom:
              secretKeyRef:
                name: guardian
                key: secret_key
