apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: discovery-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: discovery-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: discovery-api
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: discovery-api
    spec:
      containers:
      - name: discovery-api
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        resources:
{{ toYaml .Values.resources | indent 10 }}
        envFrom:
        - configMapRef:
            name: discovery-api-configs
