apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: discovery-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: discovery-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: discovery-api
  template:
    metadata:
      labels:
        app: discovery-api
    spec:
      containers:
      - name: discovery-api
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
          - name: KAFKA_BROKERS
            value: {{ .Values.kafka.brokers }}
          - name: KAFKA_TOPIC
            value: {{ .Values.kafka.topic }}
          - name: KAFKA_CONSUMER_GROUP
            value: {{ .Values.kafka.consumerGroup }}
          - name: REDIS_HOST
            value: {{ .Values.redis.host }}
          - name: PRESTO_URL
            value: {{ .Values.presto.url }}
          - name: PRESTO_CATALOG
            value: {{ .Values.presto.catalog }}
          - name: PRESTO_SCHEMA
            value: {{ .Values.presto.schema }}
