apiVersion: v1
kind: Service
metadata:
  name: discovery-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: discovery-api
spec:
  selector:
    app: discovery-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
